server:
  port: 8001
  servlet:
    context-path: /api
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**